// Pika dynamic pages: simple product details, practical guides, password, and not-found states.
import { Link } from "wouter";
import { ArticleGrid, BasicForm, ButtonLink, CtaBanner, Eyebrow } from "@/components/Blocks";
import { ASSETS, articles, bodyCopy, featureItems, featureLongCopy, richLead } from "@/data/site";

function RichBody() { return <div className="rich-body"><h3>Start with a question.</h3><p>{featureLongCopy}</p><div className="editorial-image"><img src={ASSETS.communitySearch} alt="Pika search results" /></div><h3>Read the result before you act.</h3><p>{richLead}</p><ul><li>Search for a person, a topic, or a problem.</li><li>Open the conversation instead of guessing from a notification.</li><li>Save anything you want to come back to.</li></ul><p>Good results are easy to lose when conversations move quickly. Pika gives you a simple place to keep them.</p><div className="editorial-image slim"><img src={ASSETS.conversationContext} alt="Pika conversation context and saved item" /></div><h3>Come back when you are ready.</h3><p>Use a watchlist for topics you want to follow. Use saved items for people and threads you do not want to forget.</p></div>; }

export function FeatureDetail({ slug }: { slug: string }) { const feature = featureItems.find((item) => item.slug === slug) ?? featureItems[0]; const visual = feature.slug === "watch" ? ASSETS.monitoring : feature.slug === "save" ? ASSETS.conversationContext : ASSETS.communitySearch; return <><section className="detail-hero"><div className="site-container"><Eyebrow>How Pika helps</Eyebrow><h1>{feature.title}</h1><p>{feature.description}</p><img src={visual} alt={`Pika ${feature.title.toLowerCase()} screen`} /></div></section><section className="section rich-section"><article className="narrow-container"><RichBody /></article></section><section className="section feature-detail-more"><div className="site-container"><div className="feature-detail-heading"><Eyebrow>Keep exploring</Eyebrow><h2>Other useful things Pika can do.</h2><p>{bodyCopy}</p></div><div className="feature-route-cards">{featureItems.filter((item) => item.slug !== feature.slug).map((item, index) => <Link key={item.slug} href={`/feature/${item.slug}`}><span>0{index + 1}</span><span className="feature-route-icon"><img src={item.icon} alt="" /></span><div><h2>{item.title}</h2><p>{item.description}</p></div><span className="source-button primary" aria-hidden="true"><span>See how</span></span></Link>)}</div></div></section><CtaBanner /></> }

export function ArticleDetail({ slug }: { slug: string }) { const article = articles.find((item) => item.slug === slug) ?? articles[0]; return <><section className="article-hero"><div className="site-container"><Eyebrow>Guide</Eyebrow><h1>{article.title}</h1><p>{richLead}</p><div className="article-author"><span>{article.date}</span><span>{article.author}</span></div><img src={article.image} alt="" /></div></section><section className="section rich-section"><article className="narrow-container"><RichBody /></article></section><section className="section read-more"><div className="site-container"><div className="section-intro"><Eyebrow>More guides</Eyebrow><h2>Find more useful conversations.</h2><p>Short guides for searching, watching topics, and saving the results you want to revisit.</p></div><ArticleGrid limit={3} /><div className="view-all"><ButtonLink href="/blog-articles" tone="secondary">All guides</ButtonLink></div></div></section><CtaBanner /></> }

export function PasswordPage() { return <section className="password-page"><div className="password-visual"><img src={ASSETS.generatedPasswordVisual} alt="Abstract Pika visual" /></div><div className="password-panel"><Link className="brand pika-wordmark" href="/" aria-label="Pika home"><span className="pika-mark" aria-hidden="true" /><span>Pika</span></Link><Eyebrow>Protected page</Eyebrow><h1>Protected page</h1><p>Enter the password to continue.</p><BasicForm type="password" /></div></section>; }
export function SourceNotFound() { return <section className="source-not-found"><img src="/assets/not-found-grid.png" alt="" /><div><Eyebrow>404</Eyebrow><h1>We could not find that page.</h1><p>It may have moved, or it may not exist.</p><ButtonLink href="/">Return home</ButtonLink></div></section>; }
