// Pika homepage: short, concrete product copy paired with product UI visuals.
import { Link } from "wouter";
import { ArrowUpRight, ChevronRight } from "lucide-react";
import { ArticleGrid, ButtonLink, CtaBanner, Eyebrow, FaqSection } from "@/components/Blocks";
import { ASSETS, featureItems, useCases, workflowQuestions } from "@/data/site";

const ticker = ["Search conversations", "Find people", "Watch topics", "Save threads"];

export default function Home() {
  return <>
    <section className="home-hero site-container"><div className="hero-backdrop"><img src={ASSETS.grid} alt="" /></div><div className="hero-copy" data-reveal="scale"><Eyebrow>Find better conversations</Eyebrow><h1>Find the conversations, people, and opportunities worth your attention.</h1><p>Search communities, follow topics, and save useful threads in one place.</p><div className="hero-actions"><ButtonLink href="/pricing">Get started</ButtonLink><span>or</span><ButtonLink href="/features" tone="secondary">See the product</ButtonLink></div></div><div className="hero-dashboard"><img src={ASSETS.communitySearch} alt="Pika search results for people looking for a React developer" /></div></section>
    <div className="site-container ticker">{ticker.map((item, index) => <span key={item}><i className={index % 2 ? "dark-dot" : "gradient-dot"} />{item}</span>)}</div>
    <section className="section main-features"><div className="site-container"><div className="feature-heading" data-reveal="scale"><Eyebrow>Search without digging</Eyebrow><div><h2>Ask for the thing you want to find.</h2><p>Find people looking for a developer. Find conversations about a problem. Find communities about a topic.</p></div></div><div className="step-visual" data-reveal data-reveal-delay="1"><div className="feature-steps"><article><div className="workflow-art"><img src={ASSETS.workflowQuestion} alt="Abstract 3D shape representing a search question" /></div><span>01</span><h3>Type a simple question</h3><p>Start with the person, topic, or problem you care about.</p></article><article><div className="workflow-art"><img src={ASSETS.workflowResults} alt="Abstract 3D shapes representing search results" /></div><span>02</span><h3>Read the results</h3><p>See useful conversations without opening server after server.</p></article><article><div className="workflow-art"><img src={ASSETS.workflowSave} alt="Abstract 3D bookmark shape representing saved results" /></div><span>03</span><h3>Save the good ones</h3><p>Keep a short list of people and threads to revisit.</p></article></div></div></div></section>
    <section className="section discovery"><div className="site-container"><div className="section-intro intro-left" data-reveal="scale"><Eyebrow>What you can do</Eyebrow><h2>Find it. Follow it. Come back to it.</h2></div><div className="discovery-grid" data-reveal data-reveal-delay="1">{featureItems.map((feature, index) => <Link className="discovery-card" key={feature.slug} href={`/feature/${feature.slug}`}><span className="discovery-num">0{index + 1}</span><span className="feature-icon-shell"><img src={feature.icon} alt="" /></span><h3>{feature.title}</h3><p>{feature.description}</p><span className="card-arrow"><ArrowUpRight size={18} /></span></Link>)}</div></div></section>
    <section className="assistant-section"><div className="site-container assistant-layout"><div className="assistant-visual assistant-context-visual" data-reveal data-parallax="12"><img src={ASSETS.conversationContext} alt="Focused view of a Pika conversation result with context and a save action" /></div><div className="assistant-copy" data-reveal="scale" data-reveal-delay="1"><Eyebrow>Read the context</Eyebrow><h2>See what people are talking about before you jump in.</h2><p>Open a result to read the conversation, see who is involved, and decide whether it is worth saving or following up on.</p><div className="workflow-questions">{workflowQuestions.slice(0, 3).map((question) => <span key={question}>{question}</span>)}</div></div></div></section>
    <section className="section assistant-cta"><div className="site-container assistant-cta-inner" data-reveal="scale"><div><Eyebrow>Keep up without checking everything</Eyebrow><h2>Watch a topic. Pika keeps an eye on it.</h2><p>Follow the topics and conversations you care about. Come back when there is something new to read.</p><div className="hero-actions"><ButtonLink href="/pricing">Get started</ButtonLink><span>or</span><ButtonLink href="/features" tone="secondary">See how watching works</ButtonLink></div></div><img className="watch-orbit-art" src={ASSETS.watchOrbit} alt="Abstract 3D illustration of a topic being watched for a new update" /></div></section>
    <section className="trust-section"><div className="site-container"><div className="trust-intro" data-reveal="scale"><Eyebrow>Less to dig through</Eyebrow><h2>Pika helps you get to the useful part faster.</h2><p>Search many conversations at once. Keep a watchlist. Save the people and threads you want to revisit.</p></div><div className="logo-row signal-principles" data-reveal data-reveal-delay="1"><span>Search results</span><span>Topic alerts</span><span>Saved threads</span></div></div></section>
    <section className="section compatibility"><div className="site-container compatibility-card"><div data-reveal="scale" data-parallax="8"><Eyebrow>Built around real communities</Eyebrow><h2>Discord is where communities live. Pika is where you make sense of them.</h2><p>Use Pika to find useful conversations and keep track of the ones you do not want to lose.</p><ButtonLink href="/features">See the product</ButtonLink></div><img className="community-atlas-art" src={ASSETS.communityAtlas} alt="Abstract 3D map of connected communities" data-reveal data-reveal-delay="1" /></div></section>
    <section className="section about-number"><div className="site-container numbers-layout"><div data-reveal="scale"><Eyebrow>Who Pika helps</Eyebrow><h2>For people who need to find things in communities.</h2><p>Whether you are looking for customer questions, developer work, future clients, or a topic worth tracking, Pika gives you a simple place to start.</p></div><div className="use-case-list" data-reveal data-reveal-delay="1">{useCases.slice(0, 3).map((useCase) => <article key={useCase.title}><h3>{useCase.title}</h3><p>{useCase.description}</p></article>)}</div></div></section>
    <FaqSection />
    <section className="section blog-preview"><div className="site-container" data-reveal><div className="section-head-row"><div><Eyebrow>Guides</Eyebrow><h2>Better ways to find useful conversations.</h2><p>Short guides on finding people, following topics, and saving the threads you want to revisit.</p></div><Link className="text-link" href="/blog-articles">Read guides <ChevronRight size={16} /></Link></div><ArticleGrid limit={3} /><div className="view-all"><Link className="source-button secondary" href="/blog-articles"><span>All guides</span><span className="button-round"><ArrowUpRight size={14} /></span></Link></div></div></section>
    <CtaBanner />
  </>;
}
