// Pika secondary routes: plain product copy backed by concrete examples and product-led visuals.
import { Link } from "wouter";
import { ArrowUpRight, ChevronRight } from "lucide-react";
import { ArticleGrid, BasicForm, ButtonLink, CtaBanner, Eyebrow, FaqSection, PageHero, TestimonialSection } from "@/components/Blocks";
import { ASSETS, articles, bodyCopy, featureItems, legalSections, useCases, workflowQuestions } from "@/data/site";

const productSteps = [
  { name: "Search", label: "Find something useful", detail: "Search for people, conversations, communities, or a topic you want to follow." },
  { name: "Watch", label: "Keep up", detail: "Follow a topic without checking every channel yourself." },
  { name: "Save", label: "Come back later", detail: "Keep useful threads and people in one short list." },
];

export function PricingPage() { return <><PageHero eyebrow="Get started" title="Start with something you need to find." description="A person asking for help. A conversation about a problem. A community around a topic." compact /><section className="section pricing-section"><div className="site-container pricing-cards">{productSteps.map((step, index) => <article className={`price-card ${index === 1 ? "pro" : ""}`} key={step.name}>{index === 1 && <div className="price-ribbon">How Pika works</div>}<div className="price-card-body"><div className="plan-title"><h2>{step.name}</h2><span><small>{step.label}</small></span></div><hr /><h3>{step.label}</h3><p>{step.detail}</p><ul><li>Simple questions</li><li>Useful results</li><li>One place to return to</li></ul><ButtonLink href="/contact" tone={index === 1 ? "primary" : "secondary"}>Get started</ButtonLink></div></article>)}</div></section><section className="section comparison-section"><div className="site-container"><div className="section-intro"><Eyebrow>What you can find</Eyebrow><h2>Start with a question. End with a useful result.</h2><p>{bodyCopy}</p></div><div className="comparison-table"><div className="comparison-row header"><span>You want to find</span><span><b>Search</b><small>Ask Pika</small></span><span><b>Watch</b><small>Keep up</small></span><span><b>Save</b><small>Return later</small></span></div>{[["A person", "Search by need", "Follow new requests", "Save a profile"], ["A conversation", "Search by topic", "Watch the thread", "Save the thread"], ["A community", "Search by topic", "Watch new posts", "Keep a shortlist"], ["A problem", "Search the discussion", "Follow updates", "Save examples"]].map((row) => <div className="comparison-row" key={row[0]}>{row.map((cell, index) => <span key={index}>{cell}</span>)}</div>)}</div></div></section><FaqSection /><CtaBanner /></> }

function FeatureCards({ visual = false }: { visual?: boolean }) { return <div className={`feature-route-cards ${visual ? "visual" : ""}`}>{featureItems.map((feature, index) => <Link key={feature.slug} href={`/feature/${feature.slug}`}><span>0{index + 1}</span><span className="feature-route-icon"><img src={feature.icon} alt="" /></span><div><h2>{feature.title}</h2><p>{feature.description}</p></div><span className="source-button primary" aria-hidden="true"><span>See how</span><span className="button-round"><ArrowUpRight size={14} /></span></span></Link>)}</div>; }

function AskPikaGrid() { return <section className="apps-section"><div className="site-container"><div className="section-intro"><Eyebrow>Try a search</Eyebrow><h2>Ask Pika the way you would ask a person.</h2><p>Start with the thing you want to find.</p></div><div className="apps-grid">{workflowQuestions.map((question, index) => <article key={question}><span className="app-dot" /><h4>0{index + 1}</h4><p>{question}</p></article>)}</div></div></section>; }

export function FeaturesPage() { return <><PageHero eyebrow="The product" title="A simple way to find useful conversations." description="Search for people, topics, and communities. Watch the ones you care about. Save the good results." /><section className="section"><div className="site-container"><FeatureCards visual /></div></section><section className="section feature-media"><div className="site-container"><article><img src={ASSETS.communitySearch} alt="Pika search results" /><div><Eyebrow>Search</Eyebrow><h2>Find the conversation you would otherwise miss.</h2><p>Search for a person, a problem, or a topic. Pika brings the matching conversations together.</p><Link className="text-link" href="/contact">Try a search <ChevronRight size={16} /></Link></div></article><article className="reverse"><img src={ASSETS.conversationContext} alt="Pika conversation context" /><div><Eyebrow>Read and decide</Eyebrow><h2>See the thread before you act.</h2><p>Open a result, read the conversation, and save it if you want to come back or follow up.</p><Link className="text-link" href="/contact">See a result <ChevronRight size={16} /></Link></div></article></div></section><AskPikaGrid /><CtaBanner /></> }

export function AboutPage() { return <><PageHero eyebrow="Who Pika is for" title="For people who need to find things in communities." description="Pika helps you search for useful conversations and keep up with the ones you care about." /><section className="section about-number"><div className="site-container numbers-layout"><div><Eyebrow>Use Pika when you need to</Eyebrow><h2>Find a person, a topic, a problem, or a place to look.</h2><p>Instead of reading everything, search for the conversation you need and keep a short list of the results worth returning to.</p></div><div className="about-product-visual"><img className="about-community-art" src={ASSETS.communityAtlas} alt="Abstract 3D map of connected communities" /><div className="short-note"><h3>Discord is where communities live.</h3><p>Pika is where you make sense of them.</p></div></div></div></section><section className="section timeline"><div className="site-container"><div className="section-intro"><Eyebrow>Who uses Pika</Eyebrow><h2>Useful for work that starts with a conversation.</h2></div><div className="timeline-grid">{useCases.map((useCase, index) => <article key={useCase.title}><span>0{index + 1}</span><h3>{useCase.title}</h3><p>{useCase.description}</p></article>)}</div></div></section><TestimonialSection /><CtaBanner /></> }

export function FAQPage() { return <><PageHero eyebrow="FAQ" title="Pika, in plain English." description="Find useful conversations. Follow topics. Save the results you want to return to." /><FaqSection withHelp={false} /><CtaBanner /></> }

export function BlogPage({ category }: { category?: string }) { const selectedCategory = category === "monitoring" ? "Monitoring" : category === "search" ? "Search" : "Workflow"; const filtered = category ? articles.filter((article) => article.category === selectedCategory) : articles; return <><PageHero eyebrow={category ? selectedCategory : "Guides"} title={category ? `${selectedCategory} guides` : "Better ways to find useful conversations."} description="Short, practical guides for searching, watching topics, and saving the results you want to revisit." /><section className="section blog-listing"><div className="site-container"><div className="section-head-row"><div><Eyebrow>Guides</Eyebrow><h2>{category ? `Learn to ${selectedCategory.toLowerCase()}` : "Start with the question you have."}</h2></div>{!category && <div className="filter-tabs"><Link href="/blog-articles">All</Link><Link href="/category/monitoring">Monitoring</Link><Link href="/category/search">Search</Link></div>}</div><ArticleGrid limit={category ? filtered.length : 3} /><div className="section-head-row all-article-head"><div><Eyebrow>All guides</Eyebrow><h2>Read what helps.</h2></div></div><ArticleGrid /></div></section><CtaBanner /></> }

export function ContactPage() { return <><PageHero eyebrow="Contact Pika" title="Tell us what you want to find." description="A person asking for help. A conversation about a problem. A community around a topic." /><section className="section contact-section"><div className="site-container contact-layout"><div className="contact-details"><Eyebrow>Start with a real question</Eyebrow><h2>What would you like Pika to help you find?</h2><p>Tell us what you are looking for. We will show you how Pika can make that search easier.</p><h3>Keep up without checking everything.</h3><p>Tell Pika what you want to watch. Come back when there is something new to read.</p></div><div className="contact-form-card"><Eyebrow>Contact form</Eyebrow><h2>Start your search.</h2><BasicForm /></div></div></section><CtaBanner /></> }

export function LegalPage({ title }: { title: "Privacy Policy" | "Terms & Conditions" }) { return <><PageHero eyebrow="Pika" title={title} description="Information about using Pika." compact /><section className="section legal-page"><div className="narrow-container">{legalSections.map((section) => <article key={section.title}><h2>{section.title}</h2><p>{section.text}</p></article>)}</div></section><CtaBanner /></> }

export function AdminPage({ type }: { type: "style" | "licenses" | "changelog" }) { const config = type === "style" ? { eyebrow: "Pika", title: "Design system" } : type === "licenses" ? { eyebrow: "Pika", title: "Asset information" } : { eyebrow: "Pika", title: "Changelog" }; return <><PageHero eyebrow={config.eyebrow} title={config.title} description={type === "style" ? "The visual rules used across the Pika website." : type === "licenses" ? "Information about visual assets used on the Pika website." : "Updates to the Pika website."} compact />{type === "style" && <section className="section style-guide"><div className="site-container"><div className="style-color-grid">{["Accent", "Canvas", "Ink", "Muted", "Line", "Warm", "Pink", "Violet"].map((name, index) => <article key={name} className={`swatch swatch-${index}`}><span>{name}</span></article>)}</div><div className="style-type"><h2>Typography</h2><p className="cal-example">Cal Sans <b>Aa</b> 01234567890</p><p>Rubik <b>Aa</b> 01234567890</p><h2>Keep it clear</h2><h1>Find useful conversations.</h1><h2>Watch the topics you care about.</h2><h3>Save the results you want to revisit.</h3><p>{bodyCopy}</p></div><img className="style-art" src={ASSETS.communityAtlas} alt="Abstract 3D map of connected communities" /></div></section>}{type === "licenses" && <section className="section legal-page"><div className="narrow-container"><h2>Visual assets</h2><p>This page documents the visual assets used in the Pika website.</p><h2>Icons</h2><p>Icons help people move through the product and website.</p><h2>Typography</h2><p>Cal Sans and Rubik are used across the Pika website.</p></div></section>}{type === "changelog" && <section className="section legal-page"><div className="narrow-container"><h2>Current direction</h2><p>Pika helps people find useful conversations, people, communities, and opportunities online.</p></div></section>}<CtaBanner /></> }
