// Pika shared components: direct copy that explains a useful product without abstract platform language.
import { Link } from "wouter";
import { ArrowUpRight, Check, Eye, EyeOff, Plus } from "lucide-react";
import { FormEvent, useState } from "react";
import { articles, ASSETS, faqItems } from "@/data/site";

export function Eyebrow({ children }: { children: React.ReactNode }) { return <span className="eyebrow"><i />{children}</span>; }
export function ButtonLink({ href = "/contact", children, tone = "primary" }: { href?: string; children: React.ReactNode; tone?: "primary" | "secondary" }) { return <Link href={href} className={`source-button ${tone}`}><span>{children}</span><span className="button-round"><ArrowUpRight size={14} /></span></Link>; }
export function PageHero({ eyebrow, title, description, compact = false }: { eyebrow: string; title: string; description: React.ReactNode; compact?: boolean }) { return <section className={`page-hero ${compact ? "page-hero-compact" : ""}`}><div className="site-container page-hero-inner"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1><p>{description}</p>{!compact && <ButtonLink href="/pricing">Get started</ButtonLink>}</div></section>; }
export function CtaBanner() { return <section className="cta-wrap"><div className="site-container cta-banner"><div className="cta-grid" /><div className="cta-content"><Eyebrow>Start with a search</Eyebrow><h2>Find a useful conversation today.</h2><p>Ask Pika for a person, topic, problem, or community you want to find.</p><div className="hero-actions"><ButtonLink href="/pricing">Get started</ButtonLink><span>or</span><ButtonLink href="/features" tone="secondary">See the product</ButtonLink></div></div><img className="cta-art" src={ASSETS.startSearch} alt="Abstract 3D illustration of a question becoming useful search results" /></div></section>; }
export function FaqList() { return <div className="faq-list">{faqItems.map((item, index) => <details key={item.question} open={index === 0}><summary><span>{item.question}</span><Plus size={19} /></summary><p>{item.answer}</p></details>)}</div>; }
export function FaqSection({ withHelp = true }: { withHelp?: boolean }) { return <section className="section faq-section"><div className="site-container faq-layout"><div><Eyebrow>FAQ</Eyebrow><h2>What Pika does, in plain English.</h2>{withHelp && <p className="muted-copy">Have a question? <Link href="/contact">Contact us</Link>.</p>}</div><FaqList /></div></section>; }
export function ArticleGrid({ limit }: { limit?: number }) { return <div className="article-grid">{articles.slice(0, limit ?? articles.length).map((article) => <Link className="article-card" key={article.slug} href={`/articles/${article.slug}`}><div className="article-image"><img src={article.image} alt="" /></div><div className="article-meta"><span>GUIDE</span><span>{article.date}</span></div><h3>{article.title}</h3><p>{article.author}</p></Link>)}</div>; }
export function TestimonialSection() { return <section className="section testimonials"><div className="site-container"><div className="section-intro"><Eyebrow>How Pika works</Eyebrow><h2>Search. Watch. Save.</h2><p>Use Pika to find useful conversations, keep track of topics, and return to the results you want to act on.</p></div><div className="testimonials-grid"><article className="testimonial-feature"><p className="quote-mark">01</p><blockquote>Search for people, conversations, and communities.</blockquote><div className="person"><span><b>Find</b><small>Start with a question.</small></span></div></article><article className="testimonial-small"><p>Follow a topic without opening every channel.</p><div className="person"><span><b>Watch</b><small>Come back when there is something new.</small></span></div></article><article className="testimonial-small"><p>Keep the threads and people you want to revisit.</p><div className="person"><span><b>Save</b><small>Return when you are ready.</small></span></div></article></div></div></section>; }
export function Metrics({ compact = false }: { compact?: boolean }) { const values = compact ? [["Find", "People and conversations."], ["Watch", "Topics you care about."], ["Save", "Threads to revisit."]] : [["Search", "Ask for a person, topic, or problem."], ["Watch", "Follow new conversations."], ["Save", "Keep useful results close."]]; return <div className={`metrics ${compact ? "metrics-compact" : ""}`}>{values.map(([value, label]) => <article key={value}><strong>{value}</strong><span>{label}</span><p>Simple, useful, and easy to come back to.</p></article>)}</div>; }
export function ComparisonMark({ active = true }: { active?: boolean }) { return active ? <span className="check-mark"><Check size={12} /></span> : <span className="empty-mark">×</span>; }
export function BasicForm({ type = "contact" }: { type?: "contact" | "password" }) { const [done, setDone] = useState(false); const [showPassword, setShowPassword] = useState(false); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setDone(true); }; if (done) return <p className="form-success">{type === "contact" ? "Thanks — we will be in touch." : "Incorrect password. Please try again."}</p>; return <form className={`basic-form ${type}`} onSubmit={submit}>{type === "contact" && <><input required placeholder="Name" /><input required type="email" placeholder="Email" /><textarea required placeholder="What are you trying to find?" rows={5} /></>}<span className="password-control"><input required type={showPassword ? "text" : "password"} placeholder={type === "password" ? "Password" : undefined} /><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword((state) => !state)}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></span><button className="source-button primary" type="submit"><span>{type === "contact" ? "Send message" : "Submit"}</span><span className="button-round"><ArrowUpRight size={14} /></span></button></form>; }
